run:
  # default concurrency is an available CPU number
  concurrency: 4

  timeout: 60m

  issues-exit-code: 1

  tests: true

  allow-parallel-runners: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  lll:
    line-length: 100
    tab-width: 2

linters:
  enable:
    - megacheck
    - govet
  disable:
    - maligned
    - prealloc
    - scopelint
    - unparam
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false
