version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - zerologlint
  disable:
    - prealloc
    - unparam
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    lll:
      line-length: 100
      tab-width: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
